//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentManagementSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPersonnel
    {
        
        public int p_ID { get; set; }

        [Display(Name = "Personnel Name")]
        [Required]
        public string p_Name { get; set; }

        [Display(Name = "Personnel Salary")]
        [Required]
        [Range(2000,15000)]
        public Nullable<decimal> p_Salary { get; set; }

        [Display(Name = "Personnel Birthdate")]
        [Required]
        public Nullable<System.DateTime> p_Birthdate { get; set; }

        [Display(Name = "Personnel Gender")]
        [Required]
        public Nullable<bool> p_Sex { get; set; }

        [Display(Name = "Personnel Activity Status")]
        public Nullable<bool> p_IsActive { get; set; }

        [Display(Name = "Department")]
        [Required]
        public Nullable<int> departmentID { get; set; }
        
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
