//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentManagementSystem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonal
    {
        public int p_ID { get; set; }
        public string p_Name { get; set; }
        public Nullable<decimal> p_Salary { get; set; }
        public Nullable<System.DateTime> p_BirthDate { get; set; }
        public Nullable<bool> p_Sex { get; set; }
        public Nullable<bool> p_IsActive { get; set; }
        public Nullable<bool> p_IsMarried { get; set; }
        public Nullable<int> departmentID { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
